-- =====================================================================
-- LOMAX SA | Etapa 2 - Persistencia con RDS y DynamoDB
-- Archivo : scripts/init-rds.sql
-- Autor   : jeysi702
-- Servicio: Amazon RDS - PostgreSQL 15
-- =====================================================================

CREATE TABLE IF NOT EXISTS categorias (
    categoria_id  INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    nombre        VARCHAR(50) NOT NULL,
    descripcion   TEXT,
    CONSTRAINT pk_categorias        PRIMARY KEY (categoria_id),
    CONSTRAINT uq_categorias_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS productos (
    producto_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    codigo         VARCHAR(20)  NOT NULL,
    nombre         VARCHAR(120) NOT NULL,
    descripcion    TEXT         NOT NULL,
    precio         NUMERIC(12,2) NOT NULL,
    categoria_id   INTEGER      NOT NULL,
    fecha_creacion TIMESTAMPTZ  NOT NULL DEFAULT now(),
    estado         VARCHAR(10)  NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT pk_productos           PRIMARY KEY (producto_id),
    CONSTRAINT uq_productos_codigo    UNIQUE (codigo),
    CONSTRAINT chk_productos_precio   CHECK (precio >= 0),
    CONSTRAINT chk_productos_estado   CHECK (estado IN ('PENDIENTE','PUBLICADO')),
    CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id)
                                       REFERENCES categorias (categoria_id)
                                       ON UPDATE CASCADE
                                       ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_productos_categoria ON productos (categoria_id);
CREATE INDEX IF NOT EXISTS ix_productos_estado    ON productos (estado);

\echo '--- 4.1 COLUMNAS CREADAS ---'
SELECT table_name, column_name, data_type FROM information_schema.columns WHERE table_name IN ('categorias','productos');

\echo '--- 4.2 RESTRICCIONES CREADAS ---'
SELECT conrelid::regclass::text AS tabla, conname, pg_get_constraintdef(oid) AS definicion
  FROM pg_constraint WHERE conrelid IN ('categorias'::regclass, 'productos'::regclass);
